#! /bin/sh
#
# Copyr 1990 Sun Microsystems, Inc.  
#ident	"@(#)ypxfr_1perhour.sh	1.2	00/05/01 SMI"
#
# ypxfr_1perhour.sh - Do hourly NIS map check/updates
#

PATH=/bin:/usr/bin:/usr/lib/netsvc/yp:$PATH
export PATH

# set -xv
ypxfr passwd.byname
ypxfr passwd.byuid 
