#! /bin/sh
#
# Copyr 1990 Sun Microsystems, Inc.  
#ident	"@(#)ypxfr_1perday.sh	1.2	00/05/01 SMI"
#
# ypxfr_1perday.sh - Do daily NIS map check/updates
#

PATH=/bin:/usr/bin:/usr/lib/netsvc/yp:$PATH
export PATH

# set -xv
ypxfr group.byname
ypxfr group.bygid 
ypxfr protocols.byname
ypxfr protocols.bynumber
ypxfr networks.byname
ypxfr networks.byaddr
ypxfr services.byname
ypxfr ypservers
