#!/usr/bin/sh
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)dfshares.sh	1.2	00/07/17 SMI"

# dfshares is a server utility but cachefs is a client
# filesystem, so dfshares for cachefs will do nothing.
# This utility is needed because cachefs is included in
# /etc/dfs/fstypes.

exit 0
