#! /usr/bin/perl -w

sub do_system
{
    my ($command) = @_;
    system ($command);
    if ($? != 0) {
	die "Command failed: $command";
    }
}

$filename = `/usr/lib/evolution/1.4/evolution-addressbook-export`;
if ($? != 0) {
    $! = $?;
    die $!;
}

$HOME = $ENV{"HOME"};

system ("/usr/lib/evolution/1.4/killev");
do_system ("/bin/mv ${HOME}/evolution/local/Contacts/addressbook.db ${HOME}/evolution/local/Contacts/addressbook-backup.db");
do_system ("/usr/lib/evolution/1.4/evolution-addressbook-import --input-file $filename");
do_system ("/bin/rm $filename");

