#
#ident	"@(#)Form.flash.http	5.1	01/04/04 SMI"
#
# Copyright (c) 2001 Sun Microsystems, Inc.  All Rights Reserved.
#
#############################################################################
#	Module Name:  Form.flash.http
#       Arguments:    $ARG1 - The next archive_id to use when adding archive.
#############################################################################
# This form asks for the required information for retrieving flash archives
# through HTTP.
#############################################################################

# Form-wide infomation.

form=`gettext "HTTP Retrieval"`
help=OPEN TEXT $OBJ_DIR/Sub1Help.http
altslks=true

# File used to gather output from pfinstall
`set -l VERIFYOUT="/tmp/pfinstall.flash.verify.${VPID}`

# We don't want this file to stick around
close=`rm -f ${VERIFYOUT}`

############################################################################
# This block is run when the user attempts to accept what they
# have entered.  Here, we go run pfinstall and pass the line
# that would normally end up in a pfinstall profile.  If pfinstall
# is able to verify the archive, we add it to the list and
# close this form.  Otherwise, we pop up a message and refuse
# to leave.
############################################################################
done=`
	message -w;
	set -l LOCSPEC="archive_location ${F1}";
	if [ -n "$F2" -a -n "$F3" ];
	then
		set -l LOCSPEC="${LOCSPEC} proxy $F2:$F3";
	fi;
	set -e LD_LIBRARY_PATH="$MRPATH/usr/snadm/lib";
	$MRPATH/usr/sbin/install.d/pfinstall -F ${LOCSPEC} > ${VERIFYOUT} 2> ${VERIFYOUT} ;
	if [ "${RET}" != 0 ] ;
	then
		set -l CMD="open text $OBJ_DIR/Text.flash.invalid ${VERIFYOUT}";
	else
		set -l SPEC="${ARG1}|HTTP|${F1}|${LOCSPEC}";
		echo $SPEC >> ${ARCHIVELIST};
		set -l CMD="close";
	fi;`$CMD

############################################################################
# Field: URL
# Format: "URL:  _________"
# Validation: none
############################################################################
name=`gettext "URL"`":"
nrow=1
ncol=2
frow=1
fcol=15
rows=1
columns=50
scroll=true

# default value
value=`gettext 'http://my.host.com/archive.flar'`

############################################################################
# Field: Proxy host
# Format: "Proxy Host:  _________"
# Validation: none
############################################################################
name=`gettext "Proxy Host"`":"
nrow=2
ncol=3
frow=2
fcol=15
rows=1
columns=50
scroll=true

############################################################################
# Field: Proxy Port
# Format: "Proxy Port:  _________"
# Validation: Must be numeric
############################################################################
name=`gettext "Proxy Port"`":"
nrow=3
ncol=3
frow=3
fcol=15
rows=1
columns=50
valid=`if [ -n "${F3}" ] ; then
		regex -v "$F3" '[0-9].*';
	else
		echo TRUE;
	fi;`

invalidmsg=`gettext "ERROR: Proxy port must be numeric"`


############################################################################
# SLK Buttons.  Only save, cancel, and help do stuff.
############################################################################
name= 
button=9
action=nop

name=
button=10
action=nop

name=`gettext "SAVE"`
button=11
action=done

NAME=
button=12
action=nop

name=
button=13
action=nop

name=`gettext "CANCEL"`
button=14
action=cancel

name=
button=15
action=help

name=`gettext "HELP"`
button=16
action=help
