#!/bin/sh
#
#ident	"@(#)dhcpconfig.sh	1.3	04/01/27 SMI"
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
DMDIR=/usr/lib/inet/dhcp/svcadm
L10NDIR=/usr/share/lib/locale
WBEMDIR=/usr/sadm/lib/wbem

CLASSPATH=${L10NDIR}:${DMDIR}/dhcpcli.jar:${DMDIR}/dhcpsvc.jar:${DMDIR}/dhcpcommon.jar:${WBEMDIR}/providerutility.jar
export CLASSPATH

LD_LIBRARY_PATH=${WBEMDIR}
export LD_LIBRARY_PATH

exec /usr/java/bin/java com.sun.dhcpmgr.cli.dhcpconfig.DhcpCfg "$@"
