#!/sbin/sh
#
# Copyright 2002 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)fc-fabric	1.1	04/08/31 SMI"
#
# This script is used to reconfigure fabric device(s) which were configured
# prior to boot.  The luxadm command used below is an expert level command
# and has a restrictive usage for boot time reconfiguration of fabric
# devices.  
#
# DO NOT USE the command for any other purpose.
#

if [ -s /etc/cfg/fp/fabric_WWN_map ] 
then
	/usr/sbin/luxadm -e create_fabric_device \
			 -f /etc/cfg/fp/fabric_WWN_map
else
	if [ -s /etc/cfg/fp/fabric_WWN_map.old ]
	then
		/usr/sbin/luxadm -e create_fabric_device \
				 -f /etc/cfg/fp/fabric_WWN_map.old
	fi
fi
