#!/sbin/sh
#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
# The copyright notice above does not evidence any
# actual or intended publication of such source code.
#
# ident	"@(#)fs-usr	1.7	05/08/02 SMI"

. /lib/svc/share/smf_include.sh
. /lib/svc/share/fs_include.sh

#
# Add physical swap.
#
/sbin/swapadd -1

#
# Check and remount the / (root) file system.
# For NFS mounts, force the llock option on.
#
if [ "${_INIT_ZONENAME:=`/sbin/zonename`}" = "global" ]; then
	readvfstab / < $vfstab
	checkfs $fsckdev $fstype $mountp || exit $SMF_EXIT_ERR_FATAL
	checkopt "llock" $mntopts
	mntopts='remount'

	[ -n "$otherops" ] && mntopts="${mntopts},${otherops}"
	[ "$fstype" = nfs ] && mntopts="${mntopts},llock"

	# if root dev is a read-only metadevice then fail
	case $special in
	/dev/md/dsk/*)
		dd if=/dev/null of=$special count=0 >/dev/null 2>&1 ||
		    exit $SMF_EXIT_ERR_FATAL
		;;
	esac

	mountfs -m $mountp $fstype $mntopts - || exit $SMF_EXIT_ERR_FATAL
fi

#
# Check and remount the /usr file system (formerly mounted read-only).
#
readvfstab /usr < $vfstab
if [ "$mountp" ]; then
	if [ "$fstype" = cachefs ]; then
		mountfs -O $mountp cachefs $mntopts $special ||
		    exit $SMF_EXIT_ERR_FATAL
	else
		checkopt ro $mntopts
		if [ "x$option" != xro ]; then
			checkfs $fsckdev $fstype $mountp ||
			    exit $SMF_EXIT_ERR_FATAL
			if [ "x$mntopts" != x- ]; then
				mntopts="remount,$mntopts"
			else
				mntopts="remount"
			fi

			# if usr dev is a read-only metadevice then fail
			case $special in
			/dev/md/dsk/*)
				dd if=/dev/null of=$special count=0 \
				    >/dev/null 2>&1 || exit $SMF_EXIT_ERR_FATAL
				;;
			esac

			mountfs - /usr $fstype $mntopts - ||
			    exit $SMF_EXIT_ERR_FATAL
		fi
	fi
fi

#
# Check and mount the /usr/platform file system.  This should only be
# present when a SunOS 5.5 (Solaris 2.5) or greater client is being
# administered by a SunOS 5.4 or less host.
#
readvfstab /usr/platform < $vfstab
if [ "$mountp" ]; then
	checkfs $fsckdev $fstype $mountp || exit $SMF_EXIT_ERR_FATAL
	mountfs - $mountp $fstype $mntopts - || exit $SMF_EXIT_ERR_FATAL
fi

#
# Mount the fd file systems if mount point exists.
#
readvfstab /dev/fd < $vfstab
if [ "$mountp" -a -d /dev/fd ]; then
	mountfs - /dev/fd - - - || exit $SMF_EXIT_ERR_FATAL
fi

# Clean up existing /etc/dfs/sharetab as there are no shared file systems
# at this point. This also takes care of a corrupt sharetab.

if [ -f /etc/dfs/sharetab ]; then
	> /etc/dfs/sharetab
fi

exit $SMF_EXIT_OK
