#!/sbin/sh
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
# The copyright notice above does not evidence any
# actual or intended publication of such source code.
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)identity-node	1.4	04/07/15 SMI"

. /lib/svc/share/smf_include.sh
. /lib/svc/share/net_include.sh

# Make sure that the libraries essential to this stage of booting can be found.
LD_LIBRARY_PATH=/lib; export LD_LIBRARY_PATH

#
# If DHCP was used on a primary interface then set the hostname
# that was returned. If no hostname was returned, set the name
# to be "unknown". The hostname must be set to something, because
# tooltalk will hang unless the name can be locally resolved.
# Sendmail also requires the name to be resolvable locally.
# Later, in inetsvc, we create a name "unknown" and create a entry
# in the local /etc/inet/hosts file pairing "unknown" with the IP
# address assigned by DHCP.  The use of bootparams as a fallback
# for all non-DHCP cases provides compatibility with the
# behavior of the system before netstrategy was introduced.
#
# For non-global zones, fall back to the `uname -n` value provided by the
# kernel if /etc/nodename does not exist, as is expected on an initial boot.
#

smf_netstrategy

case "$_INIT_NET_STRATEGY" in
	"dhcp") hostname=`/sbin/dhcpinfo Hostname` ;;
	"rarp") hostname=`/sbin/hostconfig -h -p bootparams`
		trap 'intr=1' 2 3
		while [ -z "$hostname" -a ! -f /etc/.UNCONFIGURED -a \
		    -z "$intr" ]; do
			echo "re-trying host configuration..."
			# Restrict this to IPv4 interfaces.
			/sbin/ifconfig -adD4 auto-revarp up
			hostname=`/sbin/hostconfig -h -p bootparams`
		done
		trap 2 3 ;;
	"none") hostname="`shcat /etc/nodename 2>/dev/null`"
       		if [ -z "$hostname" ]; then
			if [ "${_INIT_ZONENAME:=`/sbin/zonename`}" = "global" ]
			then
				hostname=`/sbin/hostconfig -h -p bootparams`
			else
				hostname=`/sbin/uname -n`
			fi
		fi ;;
esac

#
# If the netstrategy was unsuccessful and we haven't got a locally configured
# name, default to "unknown"
#
if [ -z "$hostname" ]; then
	hostname="`shcat /etc/nodename 2>/dev/null`"
	if [ -z "$hostname" ]; then
		hostname="unknown"
	fi
fi

/sbin/uname -S $hostname

echo "Hostname: `/sbin/uname -n`" > /dev/msglog

# Reset the library path now that we are past the critical stage
unset LD_LIBRARY_PATH
