#!/sbin/sh
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
# The copyright notice above does not evidence any
# actual or intended publication of such source code.
#
# ident	"@(#)keymap	1.17	04/07/15 SMI"

# This file loads keyboard mappings and initializes keyboard defaults

# At least for now, skip everything if in a non-global zone
if [ "${_INIT_ZONENAME:=`/sbin/zonename`}" = "global" ]; then

	#
	# Systems with no hardware keyboard ID will provide an eeprom value.
	#
	[ -x /usr/lib/set_keyboard_layout ] && /usr/lib/set_keyboard_layout

	# Load the keymap for the attached keyboard.
	/usr/bin/loadkeys

	# Initialize the keyboard defaults

	[ -h /dev/kbd -a -x /usr/bin/kbd ] && /usr/bin/kbd -i >/dev/null 2>&1
fi
