#!/sbin/sh
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)nfs-client	1.27	04/08/30 SMI"

#
# Start/stop client NFS service
#

. /lib/svc/share/smf_include.sh

stop_nfsclnt()
{
	/sbin/umountall -F cachefs
	/sbin/umountall -F nfs
}

case "$1" in
'start')

	/sbin/mountall -F nfs
	/sbin/mountall -F cachefs
	/sbin/swapadd
	;;

'stop')
	stop_nfsclnt
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit $SMF_EXIT_OK
