#!/sbin/sh
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)slp	1.3	04/12/16 SMI"
#
# Service Method Support Script for the SLP service
#
# - operates a proxy for slpd which brings up the JVM to run slpd
#   when required by a client; this prevents keeping JVM's alive
#   when the service is not in use.
#

. /lib/svc/share/smf_include.sh

CONF=/etc/inet/slp.conf
JAVA_BIN=/usr/j2se/bin/java
CLASSPATH=/usr/share/lib/slp/slpd.jar
MAIN_CLASS=com.sun.slp.slpd
SLPD_HOME=/usr/lib/inet
SLPD=slpd
SLPD_BIN=$SLPD_HOME/$SLPD

case "$1" in
'start')
	# Start slpd proxy (as a fragile dependency, conf file must exist)
	$SLPD_BIN -f $CONF >/dev/msglog 2>&1 &
	;;

'stop')
	# Kill the slpd proxy.
	/usr/bin/pkill -x -u 0 -P 1 -z `/sbin/zonename` $SLPD

	# If a configuration file exists signal a shutdown to the real slpd.
	[ -f $CONF  ] && {
		$JAVA_BIN -classpath $CLASSPATH \
       		    $MAIN_CLASS stop -f $CONF >/dev/msglog 2>&1 &

	       	# Give the above slpd instance a chance to signal
	       	# a shutdown to the real slpd instance. If after
	       	# this time it has hung kill it.
	       	sleep 5

	       	# The pattern must not exceed 80 chars!
	       	/usr/bin/pkill -x -f -u 0 -P 1,$$  -z `/sbin/zonename` \
	       	    "${JAVA_BIN}.*-classpath ${CLASSPATH} .*"		
	}

	# Kill the slpd proxy service contract
	smf_kill_contract $2 TERM 1
	[ $? -ne 0 ] && exit 1
	;;
*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
