#!/sbin/sh
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)svc-syseventd	1.4	04/12/16 SMI"

. /lib/svc/share/smf_include.sh

case "$1" in
'start')
	if /usr/lib/sysevent/syseventd >/dev/msglog 2>&1; then :; else
		exit
	fi

	# Establish the default framebuffer name.

	fbdev=`/usr/sbin/prtconf -F 2>/dev/null`

	if [ $? -eq 0 ]; then
		set -- /devices$fbdev*
		if [ -c $1 ]; then
			rm -f /dev/fb
			ln -s $1 /dev/fb
		fi
	fi
	;;

#
# devfsadmd and syseventconfd are started on-demand
# by syseventd. syseventd should be stopped before devfsadm and syseventconfd.
#
'stop')
	dpid=`/usr/bin/pgrep devfsadm`
	scpid=`/usr/bin/pgrep syseventconfd`
	spid=`/usr/bin/pgrep syseventd`
	zone=`/sbin/zonename`
	/usr/bin/pkill -x -u 0 -P 1 -z $zone rcm_daemon
	/usr/bin/pkill -x -u 0 -P 1 -z $zone syseventd
	/usr/bin/pkill -x -u 0 -P 1 -z $zone devfsadm
	/usr/bin/pkill -x -u 0 -P 1 -z $zone syseventconfd

	#
	# Since pkill is not atomic (may miss forking processes), also
	# kill entire service contract.
	#
	smf_kill_contract $2 TERM 1
	[ $? -ne 0 ] && exit 1
	;;	

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;

esac
exit 0
