#!/sbin/sh
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)svc-sma	1.1	06/06/15 SMI"
#
# Start method script for the net-snmp SNMP daemon
#

. /lib/svc/share/smf_include.sh

SNMPD_FILE=/etc/sma/snmp/snmpd.conf
SNMPCONFPATH=/etc/sma/snmp:/var/sma_snmp
MIBDIRS=/etc/sma/snmp/mibs

export SNMPCONFPATH
export MIBDIRS

if /usr/bin/egrep  '#DISABLE=YES' ${SNMPD_FILE} > /dev/null 2>&1; then
	echo "snmpd disabled by config file ${SNMPD_FILE}"
	svcadm disable svc:/application/management/sma
	exit $SMF_EXIT_MON_OFFLINE;
else
	/usr/sfw/sbin/snmpd 
fi
