#!/bin/sh
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)svc-oplhpd	1.1	06/06/20 SMI"

. /lib/svc/share/smf_include.sh

FMRI=svc:/platform/sun4u/oplhpd

sparc_enterprise="SUNW,SPARC-Enterprise"
OPLHPD=/usr/platform/${sparc_enterprise}/lib/sparcv9/oplhpd
platform=`/sbin/uname -i`

if [ $platform = "$sparc_enterprise" ]; then
	$OPLHPD				# Fail if can't execute
	exit				# Use oplhpd's exit status
else
	echo "$SMF_FMRI is not supported on this platform."
	exit $SMF_EXIT_ERR_CONFIG
fi

exit 0
