#!/sbin/sh
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)svc-utmpd	1.8	04/11/05 SMI"

. /lib/svc/share/smf_include.sh

[ ! -x /usr/lib/utmpd ] && exit $SMF_EXIT_ERR_CONFIG

# If a utmppipe exists, check for a utmpd process and exit
# if the daemon is already running.

if [ -p /etc/utmppipe ]; then
	ZONENAME=`/sbin/zonename`
	if /usr/bin/pgrep -x -u 0 -z $ZONENAME utmpd >/dev/null 2>&1; then
		echo "$0: utmpd is already running"
		exit 1
	fi
fi

/usr/bin/rm -f /etc/utmppipe
/usr/lib/utmpd &
