#!/bin/ksh
#
# ident	"@(#)x11-server.script	1.1	04/11/17 SMI"
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

USAGE="Usage: $0 [-d <display>] [-c <class>] <method> [-- <X server arguments>]"

PATH=/usr/bin:/usr/sbin:/usr/openwin/bin:/usr/X11/bin

#########
#
# Default values
# 
# Users must not modify this script to change them - change via SMF properties
#

DISPLAY="0"
CLASSES=""

while getopts c:d: opt; do
    case $opt in
	c)	if [ "$OPTARG" != "default" ] ; then
		    CLASSES="$CLASSES -c $OPTARG"
		fi ;;
	d)	DISPLAY="$OPTARG";;
	?)	echo $USAGE ; exit 2;;
    esac
done

shift `expr $OPTIND - 1`

METHOD=$1
if [ $# -lt 1 ] ; then
    echo $USAGE
    exit 2
fi
shift

case $METHOD in
    start)
	# Continue with rest of script
	;;
    *)
	echo "Invalid method $METHOD"
	exit 2
	;;
esac

if [ "$1" = "--" ] ; then
    shift
else
    if [ "$1" != "" ] ; then
	echo $USAGE
	exit 2
    fi
fi

# If the X server is started with SIGUSR1 set to ignore, then it
# sends SIGUSR1 to its parent process when it is ready to run
Xserver_ready() {
    exit 0
}

trap Xserver_ready USR1
(trap '' USR1 ; exec /usr/X11/bin/Xserver $CLASSES :$DISPLAY $* &)

